{0}{}{** Pillage auto. désactivé **}
{1}{}{** Pillage auto. activé **}
{100}{}{Comme tu veux.}
{101}{}{De suite.}
{102}{}{Okay.}
{103}{}{A tes ordres.}
{104}{}{Bien reçu.}
{105}{}{Tout de suite.}
{110}{}{Wouaf !}
{111}{}{Wouaf ! Wouaf !}
{1100}{}{Range ton arme, }
{1101}{}{Rangez tous vos armes.}
{1200}{}{Tu devrais te soigner, }
{1201}{}{Vous devriez tous vous soigner.}
{1210}{}{utilise un super stimpak.}
{1211}{}{utilise un stimpak.}
{1212}{}{se soigne}
{1213}{}{points d'impact.}
{1214}{}{ne parvient pas à se soigner.}
{1215}{}{est à court de médicaments.}
{1400}{}{Va piller les restes, }
{1410}{}{Ca suffit. Reviens, }
{1415}{}{Je n'ai plus assez de place.}
{1420}{}{C'est terminé !}
{1421}{}{J'ai terminé.}
{1422}{}{Fait et terminé.}
{1423}{}{C'est tout, il n'y a plus rien.}
{1424}{}{Il n'y a plus rien à piller.}
{1499}{}{Tous les membres du groupe sont surchargés.}
{1500}{}{Viens par ici,}
{1501}{}{On se regroupe !}
{1600}{}{Laisse-moi un peu de place,}
{1601}{}{On se déploie !}
{1900}{}{Passe aux balles normales,}
{1901}{}{Tout le monde passe aux balles normales !}
{1910}{}{Passe aux balles perforantes,}
{1911}{}{Tout le monde passe aux balles perforantes !}
{2000}{}{Feu à volonté !}
{2001}{}{Tirer au coup par coup !}
{2002}{}{Ordres pour l'équipe : rafales autorisées !}
{2003}{}{Ordres pour l'équipe : rafales interdites !}
