{0}{}{** PC auto-loot OFF **}
{1}{}{** PC auto-loot ON **}
{100}{}{Som du vill.}
{101}{}{På en gång.}
{102}{}{Okej.}
{103}{}{Som du beordrar.}
{104}{}{Ska ske.}
{105}{}{Med en gång.}
{110}{}{Voff!}
{111}{}{Voff! Voff!}
{1100}{}{Lägg undan ditt vapen, }
{1101}{}{Lägg tillbaka era vapen i holstren, gott folk.}
{1200}{}{Du borde läka dig själv, }
{1201}{}{Ni borde alla läka er själva nu.}
{1210}{}{använder ett super-stimpak.}
{1211}{}{använder ett stimpak.}
{1212}{}{läker}
{1213}{}{hälsopoäng.}
{1214}{}{misslyckas att hela.}
{1215}{}{har slut på läkande förnödenheter.}
{1400}{}{Plundra resterna, }
{1410}{}{Det räcker. Kom tillbaka }
{1415}{}{Jag har inte tillräckligt mycket plats för det där.}
{1420}{}{Färdigt.}
{1421}{}{Jag har gjort färdigt.}
{1422}{}{Gjort och gjort.}
{1423}{}{Det var allt.}
{1424}{}{Inget mer att plundra.}
{1499}{}{Alla gruppmedlemmar är överbelastade och kan inte plundra.}
{1500}{}{Kom hit,}
{1501}{}{Allihop, omgruppera er!}
{1600}{}{Ge mig lite utrymme,}
{1601}{}{Sprid ut er, allihop!}
{1900}{}{Switch to normal bullets,}
{1901}{}{Everyone switch to normal bullets!}
{1910}{}{Switch to armor piercing bullets,}
{1911}{}{Everyone switch to armor piercing bullets!}
{2000}{}{Burst at will!}
{2001}{}{Don't use bursts!}
{2002}{}{Party orders: burst allowed.}
{2003}{}{Party orders: burst forbidden.}
