{0}{}{** Auto-łupienie gracza WYŁ. **}
{1}{}{** Auto-łupienie gracza WŁ. **}
{100}{}{Jak sobie życzysz.}
{101}{}{Już się robi.}
{102}{}{Okej.}
{103}{}{Jak rozkażesz.}
{104}{}{Jasne.}
{105}{}{Oczywiście.}
{110}{}{Hau!}
{111}{}{Hau! Hau!}
{1100}{}{Schowaj broń, }
{1101}{}{Schowajcie bronie.}
{1200}{}{Opatrz rany, }
{1201}{}{Opatrzcie rany.}
{1210}{}{używa super stimpaka.}
{1211}{}{używa stimpaka.}
{1212}{}{leczy}
{1213}{}{punktów zdrowia.}
{1214}{}{nie udaje opatrzyć ran.}
{1215}{}{nie ma czym opatrzyć ran.}
{1400}{}{Przeszukaj zwłoki, }
{1410}{}{Wystarczy. Wracaj, }
{1415}{}{Nie mogę więcej unieść.}
{1420}{}{Zrobione.}
{1421}{}{Skończone.}
{1422}{}{Załatwione.}
{1423}{}{To było wszystko.}
{1424}{}{Nic więcej do zebrania.}
{1499}{}{Wszyscy członkowie drużyny są przeciążeni.}
{1500}{}{Podejdź tutaj,}
{1501}{}{Przegrupować się!}
{1600}{}{Zrób mi miejsca,}
{1601}{}{Rozproszyć się!}
{1900}{}{Przełącz na normalne naboje,}
{1901}{}{Niech wszysczy zmienią naboje na normalne!}
{1910}{}{Przełącz na naboje przebijające pancerz,}
{1911}{}{Niech wszysczy zmienią naboje na przebijące pancerz!}
{2000}{}{Strzelajcie seriami do woli!}
{2001}{}{Nie strzelajcie seriami!}
{2002}{}{Rozkazy dla drużyny: strzelanie seriami zezwolone.}
{2003}{}{Rozkazy dla drużyny: strzelanie seriami zabronione.}
{3000}{}{Everybody, wait here.}
