{0}{}{** Auto-³upienie gracza WY£. **}
{1}{}{** Auto-³upienie gracza W£. **}
{100}{}{Jak sobie ¿yczysz.}
{101}{}{Ju¿ siê robi.}
{102}{}{Okej.}
{103}{}{Jak rozka¿esz.}
{104}{}{Jasne.}
{105}{}{Oczywiœcie.}
{110}{}{Hau!}
{111}{}{Hau! Hau!}
{1100}{}{Schowaj broñ, }
{1101}{}{Schowajcie bronie.}
{1200}{}{Opatrz rany, }
{1201}{}{Opatrzcie rany.}
{1210}{}{u¿ywa super stimpaka.}
{1211}{}{u¿ywa stimpaka.}
{1212}{}{leczy}
{1213}{}{punktów zdrowia.}
{1214}{}{nie udaje opatrzyæ ran.}
{1215}{}{nie ma czym opatrzyæ ran.}
{1400}{}{Przeszukaj zw³oki, }
{1410}{}{Wystarczy. Wracaj, }
{1415}{}{Nie mogê wiêcej unieœæ.}
{1420}{}{Zrobione.}
{1421}{}{Skoñczone.}
{1422}{}{Za³atwione.}
{1423}{}{To by³o wszystko.}
{1424}{}{Nic wiêcej do zebrania.}
{1499}{}{Wszyscy cz³onkowie dru¿yny s¹ przeci¹¿eni.}
{1500}{}{PodejdŸ tutaj,}
{1501}{}{Przegrupowaæ siê!}
{1600}{}{Zrób mi miejsca,}
{1601}{}{Rozproszyæ siê!}
{1900}{}{Prze³¹cz na normalne naboje,}
{1901}{}{Niech wszysczy zmieni¹ naboje na normalne!}
{1910}{}{Prze³¹cz na naboje przebijaj¹ce pancerz,}
{1911}{}{Niech wszysczy zmieni¹ naboje na przebij¹ce pancerz!}
{2000}{}{Strzelajcie seriami do woli!}
{2001}{}{Nie strzelajcie seriami!}
{2002}{}{Rozkazy dla dru¿yny: strzelanie seriami zezwolone.}
{2003}{}{Rozkazy dla dru¿yny: strzelanie seriami zabronione.}
