{0}{}{** PC auto-botin OFF **}
{1}{}{** PC auto-botin ON **}
{100}{}{Como quieras.}
{101}{}{Ahora mismo.}
{102}{}{Vale.}
{103}{}{A sus órdenes.}
{104}{}{Me parece bien.}
{105}{}{En seguida.}
{110}{}{¡Guau!}
{111}{}{¡Guau Guau!}
{1100}{}{Pon tu arma de distancia, }
{1101}{}{Funda de todas sus armas, de personas.}
{1200}{}{Usted debe curarse a sí mismo, }
{1201}{}{Todos ustedes deben sanarse a si mismos ahora.}
{1210}{}{utiliza un súper estimulante.}
{1211}{}{utiliza un estimulante.}
{1212}{}{cura}
{1213}{}{puntos de golpe.}
{1214}{}{deja de hacer cualquier curación.}
{1215}{}{está fuera de la curación de suministros.}
{1400}{}{El botín de los restos, }
{1410}{}{Con eso es suficiente. Volver, }
{1415}{}{No tengo espacio suficiente para que cosas.}
{1420}{}{Hecho.}
{1421}{}{He terminado.}
{1422}{}{Dicho y hecho.}
{1423}{}{Eso fue todo.}
{1424}{}{No más de botín.}
{1499}{}{Todos los miembros del partido están sobrecargados y no puede botín.}
{1500}{}{Ven aquí,}
{1501}{}{Todos reagrupar!}
{1600}{}{Me dan un poco de espacio,}
{1601}{}{Todo el mundo se difunda!}
{1900}{}{Cambie a una de las balas,}
{1901}{}{Todo el mundo cambie a una de las balas!}
{1910}{}{Interruptor de municiones que perforan armaduras,}
{1911}{}{Todos interruptor de municiones que perforan armaduras!}
{2000}{}{Ráfaga a voluntad!}
{2001}{}{No utilice ráfagas!}
{2002}{}{Pedidos: ráfaga permitido.}
{2003}{}{Pedidos: ráfaga prohibido.}
