{0}{}{** PC auto-botin OFF **}
{1}{}{** PC auto-botin ON **}
{100}{}{Como quieras.}
{101}{}{Ahora mismo.}
{102}{}{Vale.}
{103}{}{A tus órdenes.}
{104}{}{Me parece bien.}
{105}{}{Enseguida.}
{110}{}{¡Guau!}
{111}{}{¡Guau Guau!}
{1100}{}{Guarda tu arma, }
{1101}{}{Guarden sus armas, chicos.}
{1200}{}{Deberías curarte, }
{1201}{}{Todos ustedes deberían curarse a si mismos ahora.}
{1210}{}{utiliza un superestimulante.}
{1211}{}{utiliza un estimulante.}
{1212}{}{cura}
{1213}{}{puntos de vida.}
{1214}{}{falla al hacer cualquier curación.}
{1215}{}{se ha quedado sin suministros curativos.}
{1400}{}{Saquea los restos, }
{1410}{}{Con eso es suficiente. Regresa, }
{1415}{}{No tengo espacio suficiente para más cosas.}
{1420}{}{Hecho.}
{1421}{}{He terminado.}
{1422}{}{Dicho y hecho.}
{1423}{}{Eso fue todo.}
{1424}{}{No hay más para saquear.}
{1499}{}{Todos los miembros del grupo están sobrecargados y no pueden saquear.}
{1500}{}{Ven aquí,}
{1501}{}{¡Todos, reagrúpense!}
{1600}{}{Dame un poco de espacio,}
{1601}{}{¡Todos, a dispersarse!}
{1900}{}{Cambia a balas normales,}
{1901}{}{¡Todos, cambien a balas normales!}
{1910}{}{Cambia a balas perforantes,}
{1911}{}{¡Todos, cambien a balas perforantes!}
{2000}{}{¡Ráfaga a voluntad!}
{2001}{}{¡No utilicen ráfagas!}
{2002}{}{Órdenes del grupo: ráfaga permitida.}
{2003}{}{Órdenes del grupo: ráfaga prohibida.}
