{0}{}{** Auto-saquear do PC DESLIGADO **}
{1}{}{** Auto-saquear do PC LIGADO **}
{100}{}{Como você desejar.}
{101}{}{Imediatamente.}
{102}{}{Okay.}
{103}{}{As ordens.}
{104}{}{Você entendeu.}
{105}{}{Imediatamente.}
{110}{}{Uuuf!}
{111}{}{Uuuf! Uuuf!}
{1100}{}{Guarde sua arma, }
{1101}{}{Guardem todas as suas armas, pessoal.}
{1200}{}{Você deveria se curar, }
{1201}{}{Vocês todos deveriam se curar agora.}
{1210}{}{usa um super stimpak.}
{1211}{}{usa um stimpak.}
{1212}{}{cura}
{1213}{}{pontos de dano.}
{1214}{}{falha em fazer qualquer cura.}
{1215}{}{está sem suprimentos de cura.}
{1400}{}{Saqueia os restos, }
{1410}{}{Isso é o bastante. Volte, }
{1415}{}{Eu não tenho espaço o bastante pra essa coisa.}
{1420}{}{Feito.}
{1421}{}{Eu terminei.}
{1422}{}{Feito e feito.}
{1423}{}{Isso foi tudo.}
{1424}{}{Não há mais nada pra saquear.}
{1499}{}{Todos os membros do grupo estão sobrecarregados e não podem saquear.}
{1500}{}{Venha aqui,}
{1501}{}{Reagrupem todos!}
{1600}{}{Me dê um pouco de espaço,}
{1601}{}{Todos se espalhem!}
{1900}{}{Trocar pra balas normais,}
{1901}{}{Todos troquem pra balas normais!}
{1910}{}{Troquem pra balas que perfuram armaduras,}
{1911}{}{Todos troquem pra balas que perfuram armaduras!}
{2000}{}{Explosivos a vontade!}
{2001}{}{Não usem explosivos!}
{2002}{}{Ordens do grupo: explosivo permitido.}
{2003}{}{Ordens do grupo: explosivo proibido.}
