{0}{}{** Автолут главным персонажем отключен **}
{1}{}{** Автолут главным персонажем включен **}
{100}{}{As you wish.}
{101}{}{Right away.}
{102}{}{Okey.}
{103}{}{At your orders.}
{104}{}{You got it.}
{105}{}{At once.}
{110}{}{Woof!}
{111}{}{Woof! Woof!}
{1100}{}{Put your weapon away, }
{1101}{}{Holster all your weapons, people.}
{1200}{}{You should heal yourself, }
{1201}{}{You should all heal yourselves now.}
{1210}{}{uses a super stimpak.}
{1211}{}{uses a stimpak.}
{1212}{}{heals}
{1213}{}{hit points.}
{1214}{}{fails to do any healing.}
{1215}{}{is out of healing supplies.}
{1400}{}{Loot the remains, }
{1410}{}{That's enough. Come back, }
{1415}{}{I don't have enough room for that stuff.}
{1420}{}{Done.}
{1421}{}{I've finished.}
{1422}{}{Done and done.}
{1423}{}{That was all.}
{1424}{}{No more to loot.}
{1499}{}{All party members are overloaded and can't loot.}
{1500}{}{Come here,}
{1501}{}{Everyone regroup!}
{1600}{}{Give me some room,}
{1601}{}{Everyone spread!}
{1900}{}{Switch to normal bullets,}
{1901}{}{Everyone switch to normal bullets!}
{1910}{}{Switch to armor piercing bullets,}
{1911}{}{Everyone switch to armor piercing bullets!}
{2000}{}{Burst at will!}
{2001}{}{Don't use bursts!}
{2002}{}{Party orders: burst allowed.}
{2003}{}{Party orders: burst forbidden.}
