{0}{}{** PC auto-saccheggio OFF **}
{1}{}{** PC auto-saccheggio ON **}
{100}{}{Come desideri.}
{101}{}{Subito.}
{102}{}{Ok.}
{103}{}{Ai tuoi ordini.}
{104}{}{Va bene.}
{105}{}{Una cosa alla volta.}
{110}{}{Uff!}
{111}{}{Uff! Uff!}
{1100}{}{Posa le tue armi, }
{1101}{}{Gente, mettete le armi al sicuro.}
{1200}{}{Dovresti curarti, }
{1201}{}{Dovresti curarti ora.}
{1210}{}{usa un super stimpak.}
{1211}{}{usa un stimpak.}
{1212}{}{curati}
{1213}{}{punti ferita.}
{1214}{}{fallisci nel curarti.}
{1215}{}{e' senza le scorte curative.}
{1400}{}{Razzia i resti, }
{1410}{}{Basta cosi'. Torna indietro, }
{1415}{}{Non ho piu' spazio per quelle cose.}
{1420}{}{Fatto.}
{1421}{}{Ho finito.}
{1422}{}{Fatto eeee fatto.}
{1423}{}{Fatto tutto.}
{1424}{}{Basta saccheggio.}
{1499}{}{Tutti i membri del party sono sovraccarichi e non possono saccheggiare.}
{1500}{}{Vieni qui',}
{1501}{}{Raggruppatevi!}
{1600}{}{Dammi piu' spazio,}
{1601}{}{Sparpagliatevi!}
{1900}{}{Usa proiettili normali,}
{1901}{}{Usate tutti proiettili normali!}
{1910}{}{Passa a proiettili perforanti,}
{1911}{}{Usate proiettili perforanti!}
{2000}{}{Fuoco a volonta'!}
{2001}{}{Non usare la raffica!}
{2002}{}{Ordini Party: raffica permessa.}
{2003}{}{Ordini Party: raffica proibita.}
{3000}{}{Everybody, wait here.}
