# Misc Messages
{0}{}{** PC auto-loot OFF **}
{1}{}{** PC auto-loot ON **}

# NPC random responses
{100}{}{As you wish.}
{101}{}{Right away.}
{102}{}{Okey.}
{103}{}{At your orders.}
{104}{}{You got it.}
{105}{}{At once.}

# put weapon away
{1100}{}{Put your weapon away, }
{1101}{}{Holster all your weapons, people.}

# Heal yourself
{1200}{}{You should heal yourself, }
{1201}{}{You should all heal yourselves now.}

# Misc healing messages
{1210}{}{uses a super stimpak.}
{1211}{}{uses a stimpak.}
{1212}{}{heals}
{1213}{}{hit points.}
{1214}{}{fails to do any healing.}
{1215}{}{is out of healing supplies.}

# Loot bodies
{1400}{}{Loot the remains, }
# Cancel looting
{1410}{}{That's enough. Come back, }
# Can't carry anymore
{1415}{}{I don't have enough room for that stuff.}

# Looting done
{1420}{}{Done.}
{1421}{}{I've finished.}
{1422}{}{Done and done.}
{1423}{}{That was all.}
{1424}{}{No more to loot.}
# An overloaded party can't loot bodies
{1499}{}{All party members are overloaded and can't loot.}

# Regroup party
{1500}{}{Come here,}
{1501}{}{Everyone regroup!}
# Spread out party
{1600}{}{Give me some room,}
{1601}{}{Everyone spread!}

# Swich ammo type
{1900}{}{Switch to normal bullets,}
{1901}{}{Everyone switch to normal bullets!}
{1910}{}{Switch to armor piercing bullets,}
{1911}{}{Everyone switch to armor piercing bullets!}

# Burst, floats
{2000}{}{Burst at will!}
{2001}{}{Don't use bursts!}
# Burst, display
{2002}{}{Party burst mode: allowed.}
{2003}{}{Party burst mode: forbidden.}
