# Misc Messages
{0}{}{** Spieler Plündert automatisch: AUS **}
{1}{}{** Spieler Plündert automatisch: AN **}

# NPC random responses
{100}{}{Wie du willst.}
{101}{}{Sofort.}
{102}{}{Klar doch..}
{103}{}{Wie du wünscht.}
{104}{}{Wird gemacht.}
{105}{}{Sicher doch.}

# dogs
{110}{}{Wuff!}
{111}{}{Wuff! Wuff!}

# put weapon away
{1100}{}{Steck deine Waffe weg, }
{1101}{}{Holstert eure Waffen, Leute.}

# Heal yourself
{1200}{}{Du solltest dich heilen, }
{1201}{}{Ihr solltet euch jetzt alle heilen.}

# Misc healing messages
{1210}{}{benutzt ein Super-Stimpak.}
{1211}{}{benutzt ein Stimpak.}
{1212}{}{heilt}
{1213}{}{Trefferpunkte.}
{1214}{}{scheitert sich zu heilen.}
{1215}{}{hat keine Heilmittel mehr.}

# Loot bodies
{1400}{}{Plünder die Überreste, }
# Cancel looting
{1410}{}{Das reicht, komm zurück, }
# Can't carry anymore
{1415}{}{Ich habe nicht genug Platz für das ganze Zeug.}

# Looting done
{1420}{}{Fertig.}
{1421}{}{Ich bin fertig.}
{1422}{}{Fix und fertig!}
{1423}{}{Das war alles.}
{1424}{}{Nichts mehr zu plündern.}
# An overloaded party can't loot bodies
{1499}{}{Alle Gruppenmitglieder sind überladen und können nicht mehr plündern.}

# Regroup party
{1500}{}{Komm her, }
{1501}{}{Alles neu gruppieren!}
# Spread out party
{1600}{}{Mach mir Platz, }
{1601}{}{Verteilt euch alle etwas!}

# Swich ammo type
{1900}{}{Wechsel zu normaler Munition, }
{1901}{}{Wechselt alle zu normaler Munition!}
{1910}{}{Wechsel zu panzerbrechender Munition, }
{1911}{}{Wechselt alle zu panzerbrechender Munition!}

# Burst, floats
{2000}{}{Feuert was das Zeug hält!}
{2001}{}{Munition sparen Leute!}
# Burst, display
{2002}{}{Gruppe: Salvenmodus erlaubt.}
{2003}{}{Gruppe: Salvenmodus verboten.}
