{0}{}{** Spieler Plündert automatisch: AUS **}
{1}{}{** Spieler Plündert automatisch: AN **}
{100}{}{Wie du meinst.}
{101}{}{Sofort.}
{102}{}{Klar doch..}
{103}{}{Wie du wünscht.}
{104}{}{Wird gemacht.}
{105}{}{Sicher doch.}
{110}{}{Wuff!}
{111}{}{Wuff! Wuff!}
{1100}{}{Steck deine Waffe weg, }
{1101}{}{Holstert eure Waffen, Leute.}
{1200}{}{Du solltest dich heilen, }
{1201}{}{Ihr solltet euch jetzt alle heilen.}
{1210}{}{benutzt ein Super-Stimpak.}
{1211}{}{benutzt ein Stimpak.}
{1212}{}{heilt}
{1213}{}{Trefferpunkte.}
{1214}{}{scheitert sich zu heilen.}
{1215}{}{hat keine Heilmittel mehr.}
{1400}{}{Plünder die Überreste, }
{1410}{}{Das reicht, komm zurück, }
{1415}{}{Ich habe nicht genug Platz für das ganze Zeug.}
{1420}{}{Fertig.}
{1421}{}{Ich bin fertig.}
{1422}{}{Fix und fertig!}
{1423}{}{Das war alles.}
{1424}{}{Nichts mehr zu plündern.}
{1499}{}{Alle Gruppenmitglieder sind überladen und können nicht mehr plündern.}
{1500}{}{Komm her, }
{1501}{}{Alles neu gruppieren!}
{1600}{}{Mach mir Platz, }
{1601}{}{Verteilt euch alle etwas!}
{1900}{}{Wechsel zu normaler Munition, }
{1901}{}{Wechselt alle zu normaler Munition!}
{1910}{}{Wechsel zu panzerbrechender Munition, }
{1911}{}{Wechselt alle zu panzerbrechender Munition!}
{2000}{}{Feuert was das Zeug hält!}
{2001}{}{Munition sparen Leute!}
{2002}{}{Gruppe: Salvenmodus erlaubt.}
{2003}{}{Gruppe: Salvenmodus verboten.}
